# This is the configuration file for Jekyll, which is a program "built in" 
# to GitHub that transforms files for web output (e.g. Markdown to HTML).
# The Jekyll documentation is useless for noobs; try this tutorial instead:
# https://www.andrewmunsell.com/tutorials/jekyll-by-example/tutorial
exclude: [Src, Lib, Visual Studio Integration]

# Jekyll settings
markdown: redcarpet
encoding: UTF-8
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"
safe: true
lsi: false

# Custom vars
paginate_prefix: "blog/" # needed for Older/Newer buttons to work right

# Poole/Hyde settings
title:       "Loyc"                      # shown in large text
description: "Language of your choice"   # shown under the title
version: (I changed Hyde not to display this)
url:     "http://loyc.net"               # Used by the Atom feed
baseurl: ""                              # grep "site.baseurl" to see how it is used
github:
  repo:  https://github.com/qwertie/Loyc # "GitHub project" link on sidebar
