version: 2.4.0.{build}

before_build:
    - nuget restore Loyc-Slim.sln

build_script:
    # First, set some environment variables.
    # SEMVER is set manually. Not sure how this can be automated.
    - set SEMVER=23.4.0
    - echo %APPVEYOR_REPO_TAG%
    # Build packages as SEMVER-ci{build}
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:SEMVER; } else { $env:PKG_VERSION = "$($env:SEMVER)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }
    - echo %PKG_VERSION%

    # Build the Loyc libraries in release mode, for all possible configurations.
    - msbuild /p:Configuration=Release.NET45 Loyc-Slim.sln
    - msbuild /p:Configuration=Release.NET4 Loyc-Slim.sln
    - msbuild /p:Configuration=Release.NET35 Loyc-Slim.sln

after_build:
    # Package the Loyc.Essentials library
    - nuget pack -Version %PKG_VERSION% Core\Loyc.Essentials.nuspec
    # Package ends up in Loyc.Essentials.$PKG_VERSION.nupkg

    # Package the Loyc.Collections library
    - nuget pack -Version %PKG_VERSION% Core\Loyc.Collections.nuspec
    # Package ends up in Loyc.Collections.$PKG_VERSION.nupkg

    # Package the Loyc.Math library
    - nuget pack -Version %PKG_VERSION% Core\Loyc.Math.nuspec
    # Package ends up in Loyc.Math.$PKG_VERSION.nupkg

    # Package the Loyc.Syntax library
    - nuget pack -Version %PKG_VERSION% Core\Loyc.Syntax.nuspec
    # Package ends up in Loyc.Syntax.$PKG_VERSION.nupkg

    # Package the Loyc.Utilities library
    - nuget pack -Version %PKG_VERSION% Core\Loyc.Utilities.nuspec
    # Package ends up in Loyc.Utilities.$PKG_VERSION.nupkg

    # Package the LoycCore libraries
    - nuget pack -Version %PKG_VERSION% Core\LoycCore.nuspec
    # Package ends up in LoycCore.$PKG_VERSION.nupkg

    # Package the ECSharp library
    - nuget pack -Version %PKG_VERSION% ECSharp.nuspec
    # Package ends up in ECSharp.$PKG_VERSION.nupkg

    # Package the LeMP binary
    - nuget pack -Version %PKG_VERSION% LeMP.nuspec
    # Package ends up in LeMP.$PKG_VERSION.nupkg

test_script:
    # Unfortunately, test set 8 (LLLPG) sometimes fails due to nondeterminism.
    # - Bin\Release.NET45\Tests.exe 12345
    # - Bin\Release.NET45\Tests.exe 67

assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

artifacts:
    - path: '*.nupkg'
      name: nupkgs

# Uncomment the section below to push the NuGet
# package whenever a git tag is pushed.
#deploy:
#    - provider: NuGet
#      server:
#      api_key:
#          secure: Encrypted key goes here. Use https://ci.appveyor.com/tools/encrypt to encrypt your NuGet API key.
#      skip_symbols: true
#      artifact: /.*\.nupkg/
#      on:
#          branch: master # Release from master branch only.
#          appveyor_repo_tag: true # Deploy on tag push only.
